(def coins 0)
(while true
  (def zx (.x (.pos this)))
  (def zy (.y (.pos this)))
  (.moveXY this (+ zx 7) (+ zy 20))
  (.bash this (.findNearest this (.findEnemies this)))
  (.moveXY this (+ zx 22) (+ zy 59))
  (def coins (inc coins))
  (.moveXY this (+ zx 34) (+ zy 22))
  (.say this coins)
  (.wait this 2)
  (.moveXY this (+ zx 40) zy)
  (.say this "Sesame")
  (.moveXY this (+ zx 60) zy))
