(def slide 10)
(def switch 6)
(def skip 9)
(def steps 1)
(def sideSteps 1)
(def xpl 4)
(def ypl 6)
(def ssn 1)
(while (<= steps 35)
  (.moveXY this (* steps xpl) (* sideSteps ypl))
  (def sideSteps (+ sideSteps ssn))
  (if (= (mod steps skip) 0)
    (def sideSteps (+ sideSteps ssn)))
  (def steps (+ steps 1))
  (if (> sideSteps slide)
    (def sideSteps (- sideSteps slide))
    (if (< sideSteps 1)
      (def sideSteps (+ sideSteps slide))))
  (if (= (mod steps switch) 0)
    (def ssn (- 0 ssn))))
